name: Push Docker image to GitHub Packages

on:
  push:
    branches:
      - master
    paths:
      - "texlive-ja.Dockerfile"
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: texlive-ja.Dockerfile
          provenance: false
          push: true
          tags: "ghcr.io/tatsumi0000/texlive-ja-devcontainer-template/texlive-ja:latest"
